name: KTStudyAppBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Clean and Build with Gradle
        run: ./gradlew cleanBuildCache && ./gradlew build

      - name: Run tests
        run: ./gradlew test


      - name: Run tests
        run: ./gradlew test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: KTStudyApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
